name: Local CI/CD with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build & Save Docker Image
        run: |
          docker-compose build
          docker save -o my-app.tar fashion-media

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-app.tar

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i my-app.tar

      - name: Stop & Remove old container
        run: docker-compose down || true

      - name: Run Docker Compose
        run: docker-compose up --build -d
