name: Local CI/CD with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Enable BuildKit & Build Docker Image
        run: |
          export DOCKER_BUILDKIT=1
          docker-compose build
          docker save -o my-app.tar fashion-media_api  # Đảm bảo tên này đúng

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-app.tar

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Install Docker & Docker Compose (if not installed)
        run: |
          if ! command -v docker-compose &> /dev/null
          then
            echo "Installing Docker Compose..."
            sudo apt-get update
            sudo apt-get install -y docker-compose
          fi

      - name: Download Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i my-app.tar

      - name: Recreate .env file (Ensure it exists)
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Stop & Remove old container
        run: docker-compose down || true

      - name: Run Docker Compose
        run: docker-compose up --build -d
