name: Local CI/CD with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Enable BuildKit & Build Docker Image
        run: |
          export DOCKER_BUILDKIT=1
          docker-compose build
          docker save -o my-app.tar fashion-media_api  # Đảm bảo tên này đúng

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-app.tar

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Install Docker & Docker Compose (if not installed)
        shell: powershell
        run: |
          if (-Not (Get-Command docker-compose -ErrorAction SilentlyContinue)) {
            Write-Output "Docker Compose is not installed. Installing..."
            Invoke-WebRequest -Uri "https://github.com/docker/compose/releases/latest/download/docker-compose-windows-x86_64.exe" -OutFile "$env:ProgramFiles\Docker\docker-compose.exe"
             Write-Output "Docker Compose installed successfully!"
            } else {
            Write-Output "Docker Compose is already installed."
            }

      - name: Download Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i my-app.tar

      - name: Recreate .env file (Ensure it exists)
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Stop & Remove old container
        shell: powershell
        run: |
            docker-compose down
            if ($?) { Write-Output "Docker Compose stopped successfully" } else { Write-Output "Ignoring error" }

      - name: Run Docker Compose
        run: docker-compose up --build -d
